Repository option-t/option-t, pull requests merged in 2020-04, with the labels that each got.

#608 Implement flatten() for PlainResult
  __tests__/PlainResult/flatten.test.js
  src/PlainResult/flatten.ts
  tools/pkg_files.json
Labels: A-API, I-enhancement

#609 Add more test cases
  __tests__/PlainOption/and_then.test.js
  __tests__/PlainOption/map_or_else.test.js
  __tests__/PlainOption/unwrap.test.js
  __tests__/PlainResult/unwrap.test.js
  __tests__/PlainResult/unwrap/unwrap_err.test.js
  __tests__/PlainResult/unwrap/unwrap_ok.test.js
Labels: A-API, I-enhancement

#610 Remove renamer-cli from depdendencies
  Makefile
  package.json
  tools/extension_renamer.js
  yarn.lock
Labels: A-infrastructure, I-cleanup

#611 Export flatten() fron PlainResult/index
  src/PlainResult/index.ts
Labels: A-API, I-enhancement

#619 Change my github id
  package.json
Labels: A-documentation, I-enhancement

#624 Run to test for 'exports' field in package.json on GitHub Actions
   .github/workflows/ci_packaging.yml
  .editorconfig
Labels: A-infrastructure, I-refactor

#625 Revert "Run to test for 'exports' field in package.json on GitHub Actions"
   .github/workflows/ci_packaging.yml
  .editorconfig
Labels: A-infrastructure, I-bug

#627 Run to test for 'exports' field in package.json on GitHub Actions
  .editorconfig
  .github/workflows/ci_packaging.yml
Labels: A-infrastructure, I-enhancement
