Repository option-t/option-t, pull requests merged in 2023-02, with the labels that each got.

#1539 Various improve documentations
  docs/README.md
  docs/idiom/README.md
  docs/idiom/unwrap_ok_or_throw_err.md
  docs/operators_reverse_index.md
  docs/public_api_list.md
  tools/generate_import_path_list_markdown.mjs
  tools/pkg_files.json
Labels: I-enhancement, A-documentation

#1540 Simplify README.md
  README.md
  docs/README.md
  docs/deprecated_apis.md
  docs/how_to_import.md
  tools/pkg_files.json
Labels: A-documentation, I-refactor

#1541 Add 'Comparison with other similar packages' section to README
  README.md
Labels: I-enhancement, A-documentation

#1476 Implement `fromPromiseSettledResultToResult()`
  __tests__/PlainResult/from_promise_settled_result.test.mjs
  docs/idiom/README.md
  docs/idiom/from_promise_settled_result.md
  docs/public_api_list.md
  src/PlainResult/fromPromiseSettledResult.ts
  tools/pkg_files.json
  tools/public_api/table.mjs
  tsconfig.base.json
Labels: I-enhancement, A-API

#1543 Expose `lib/ClassicOption` and `lib/ClassicResult`
  src/Option.ts
  src/Result.ts
  tools/package_json_rewriter/transformer/add_exports_field/compatibility.mjs
  tools/public_api/table.mjs
Labels: I-enhancement, A-API

#1544 Don't export compat alias from `Classic*`
  src/ClassicOption/index.ts
  src/ClassicResult/index.ts
  src/Option.ts
  src/Result.ts
Labels: A-API, I-cleanup

#1547 Remove some deprecations
  src/PlainOption/Option.ts
  src/PlainResult/Result.ts
  src/PlainResult/unwrapOrThrowError.ts
Labels: A-API, I-cleanup

#1548 asMut should check whether the passed value is frozen
  __tests__/PlainOption/as_mut.test.mjs
  __tests__/PlainOption/drop.test.mjs
  __tests__/PlainResult/as_mut.test.mjs
  __tests__/PlainResult/drop/test_drop_both.test.mjs
  __tests__/PlainResult/drop/test_drop_err.test.mjs
  __tests__/PlainResult/drop/test_drop_ok.test.mjs
  src/PlainOption/asMut.ts
  src/PlainOption/drop.ts
  src/PlainResult/asMut.ts
  src/PlainResult/drop.ts
  src/internal/ErrorMessage.ts
  src/internal/assert.ts
Labels: I-enhancement, A-API

#1549 Improve inline documents for PlainResult/PlainOption
  src/PlainOption/Option.ts
  src/PlainResult/Result.ts
Labels: I-enhancement, A-documentation

#1550 Move _unwrap_ to next to the `PlainResult` type definition
  src/PlainResult/Result.ts
  src/PlainResult/expect.ts
  src/PlainResult/index.ts
  src/PlainResult/internal/ErrorMessage.ts
  src/PlainResult/unwrap.ts
  tools/pkg_files.json
  tools/public_api/table.mjs
Labels: A-API, I-refactor

#1551 Stop to use deprecated path in tests for PlainResult
  __tests__/ClassicResult/compat.test.mjs
  __tests__/PlainOption/ok_or.test.mjs
  __tests__/PlainOption/ok_or_else.test.mjs
  __tests__/PlainResult/equal.test.mjs
  __tests__/PlainResult/expect/test_expect_err.test.mjs
  __tests__/PlainResult/expect/test_expect_ok.test.mjs
  __tests__/PlainResult/from_promise_settled_result.test.mjs
  __tests__/PlainResult/try_catch/try_catch.test.mjs
  __tests__/PlainResult/try_catch/try_catch_with_ensure_error.test.mjs
  __tests__/PlainResult/try_catch_async/try_catch_async.test.mjs
  __tests__/PlainResult/try_catch_async/try_catch_with_ensure_error_async.test.mjs
  __tests__/PlainResult/unwrap/unwrap_err.test.mjs
  __tests__/PlainResult/unwrap/unwrap_ok.test.mjs
Labels: A-internal, I-cleanup

#1552 Move _unwrap_ to next to the `PlainOption` type definition
  src/PlainOption/Option.ts
  src/PlainOption/expect.ts
  src/PlainOption/index.ts
  src/PlainOption/internal/ErrorMessage.ts
  src/PlainOption/unwrap.ts
  src/PlainResult/Result.ts
  tools/pkg_files.json
  tools/public_api/table.mjs
Labels: A-API, I-refactor

#1553 Stop to use deprecated path in tests for PlainOption
  __tests__/ClassicOption/compat.test.mjs
  __tests__/PlainOption/and_then.test.mjs
  __tests__/PlainOption/equal.test.mjs
  __tests__/PlainOption/expect.test.mjs
  __tests__/PlainOption/or_else_async.test.mjs
  __tests__/PlainOption/unwrap.test.mjs
Labels: A-internal, I-cleanup

#1554 Move _unwrap_ and _expect_ to next to the `Nullable`/`Undefinable`/`Maybe` type definition
  src/Maybe/Maybe.ts
  src/Maybe/expect.ts
  src/Maybe/index.ts
  src/Maybe/unwrap.ts
  src/Nullable/Nullable.ts
  src/Nullable/expect.ts
  src/Nullable/index.ts
  src/Nullable/unwrap.ts
  src/Undefinable/Undefinable.ts
  src/Undefinable/expect.ts
  src/Undefinable/index.ts
  src/Undefinable/unwrap.ts
  tools/public_api/table.mjs
Labels: A-API, I-refactor

#1555 Clarify deprecated items guide documents
  src/PlainOption/index.ts
  src/PlainResult/index.ts
Labels: A-documentation, I-cleanup

#1558 Fix CI fatal error for `make test_package_install` job
  .github/workflows/_ci.yaml
Labels: I-bug, A-ops/CI

#1559 Remove unused entries from .eslintignore
  .eslintignore
Labels: I-cleanup, A-tools/lint

#1561 Recover tools/publish/.npmrc
  tools/publish/.npmrc
Labels: A-ops/release-engineering, I-bug/regression

#1562 Add compat path for `PlainResult/fromPromiseSettledResult`
  packages/api_tests/__tests__/__snapshots__/exposed_path.test.mjs.md
  packages/api_tests/__tests__/__snapshots__/exposed_path.test.mjs.snap
  packages/api_tests/__tests__/exposed_path_table.mjs
  packages/option-t/package.json
  packages/option-t/tools/public_api/table.mjs
Labels: I-enhancement, A-API

#1564 Back `Classic*` to to ES5 class idiom to avoid test errors
  packages/option-t/src/ClassicOption/ClassicOption.js
  packages/option-t/src/ClassicResult/ClassicResult.js
Labels: I-enhancement, A-internal

#1565 Remove irregular code path to generate compat exports
  package-lock.json
  packages/api_tests/__tests__/exposed_path_table.mjs
  packages/api_tests/package.json
  packages/option-t/tools/package_json_rewriter/main.mjs
  packages/option-t/tools/package_json_rewriter/transformer/add_exports_field/ExportEntry.mjs
  packages/option-t/tools/package_json_rewriter/transformer/add_exports_field/compatibility.mjs
  packages/option-t/tools/public_api/ExposedPath.mjs
  packages/option-t/tools/public_api/table.mjs
Labels: A-internal, I-cleanup

#1566 Fix the regression: the published package does not contain any docs
  Makefile
  packages/option-t/Makefile
Labels: A-ops/release-engineering, I-bug/regression

#1569 Implement `toNullable()` & `toUndefinable` for `PlainResult`
  packages/api_tests/__tests__/PlainResult/to_nullable/from_err.test.mjs
  packages/api_tests/__tests__/PlainResult/to_nullable/from_ok.test.mjs
  packages/api_tests/__tests__/PlainResult/to_undefinable/from_err.test.mjs
  packages/api_tests/__tests__/PlainResult/to_undefinable/from_ok.test.mjs
  packages/api_tests/__tests__/PlainResult/unwrap_or/err.test.mjs
  packages/api_tests/__tests__/PlainResult/unwrap_or/ok.test.mjs
  packages/api_tests/__tests__/__snapshots__/exposed_path.test.mjs.md
  packages/api_tests/__tests__/__snapshots__/exposed_path.test.mjs.snap
  packages/api_tests/__tests__/exposed_path_table.mjs
  packages/option-t/package.json
  packages/option-t/src/PlainResult/toNullable.ts
  packages/option-t/src/PlainResult/toUndefinable.ts
  packages/option-t/src/PlainResult/unwrapOr.ts
  packages/option-t/tools/pkg_files.json
  packages/option-t/tools/public_api/table.mjs
Labels: I-enhancement, A-API

#1570 Hide unwrapErrOrFromResult()
  Makefile
  packages/api_tests/Makefile
  packages/api_tests/__tests__/PlainResult/unwrap_or/err.test.mjs
  packages/api_tests/__tests__/__snapshots__/exposed_path.test.mjs.md
  packages/api_tests/__tests__/__snapshots__/exposed_path.test.mjs.snap
  packages/option-t/src/PlainResult/internal/unwrapErrOr.ts
  packages/option-t/src/PlainResult/toNullable.ts
  packages/option-t/src/PlainResult/toUndefinable.ts
  packages/option-t/src/PlainResult/unwrapOr.ts
  packages/option-t/tools/pkg_files.json
Labels: I-enhancement, A-API

#1571 Sort names with other type conversion operators
  packages/api_tests/__tests__/PlainResult/to_nullable/from_err.test.mjs
  packages/api_tests/__tests__/PlainResult/to_nullable/from_ok.test.mjs
  packages/api_tests/__tests__/PlainResult/to_undefinable/from_err.test.mjs
  packages/api_tests/__tests__/PlainResult/to_undefinable/from_ok.test.mjs
  packages/api_tests/__tests__/__snapshots__/exposed_path.test.mjs.md
  packages/api_tests/__tests__/__snapshots__/exposed_path.test.mjs.snap
  packages/option-t/src/PlainResult/toNullable.ts
  packages/option-t/src/PlainResult/toUndefinable.ts
Labels: I-enhancement, A-API

#1572 Implement `toPlainResult` for `Nullable<T>`
  docs/public_api_list.md
  packages/api_tests/__tests__/Nullable/to_plain_result/to_err.test.mjs
  packages/api_tests/__tests__/Nullable/to_plain_result/to_ok.test.mjs
  packages/api_tests/__tests__/__snapshots__/exposed_path.test.mjs.md
  packages/api_tests/__tests__/__snapshots__/exposed_path.test.mjs.snap
  packages/api_tests/__tests__/exposed_path_table.mjs
  packages/option-t/package.json
  packages/option-t/src/Nullable/toPlainResult.ts
  packages/option-t/tools/pkg_files.json
  packages/option-t/tools/public_api/table.mjs
Labels: I-enhancement, A-API

#1574 Ensure package.json is valid to fix a random failure by pasing error package.json
  packages/option-t/Makefile
Labels: I-bug, A-ops/CI

#1575 Implement `toPlainResult` for `Undefinable<T>`
  docs/public_api_list.md
  packages/api_tests/__tests__/Undefinable/to_plain_result/to_err.test.mjs
  packages/api_tests/__tests__/Undefinable/to_plain_result/to_ok.test.mjs
  packages/api_tests/__tests__/__snapshots__/exposed_path.test.mjs.md
  packages/api_tests/__tests__/__snapshots__/exposed_path.test.mjs.snap
  packages/api_tests/__tests__/exposed_path_table.mjs
  packages/option-t/package.json
  packages/option-t/src/Undefinable/toPlainResult.ts
  packages/option-t/tools/pkg_files.json
  packages/option-t/tools/public_api/table.mjs
Labels: I-enhancement, A-API

#1576 Deprecate `toOptionFromOk()` & `toOptionFromErr()` which are exported from `PlainResult/index`
  packages/option-t/src/PlainResult/index.ts
Labels: I-enhancement, A-API

#1583 Implement alternative that does not use `PlainOption` for `ClassicOption/compat`
  docs/wrapper_objects.md
  packages/api_tests/__tests__/ClassicOption/compat/to_maybe.test.mjs
  packages/api_tests/__tests__/ClassicOption/compat/to_nullable.test.mjs
  packages/api_tests/__tests__/ClassicOption/compat/to_plain_option.test.mjs
  packages/api_tests/__tests__/ClassicOption/compat/to_undefinable.test.mjs
  packages/api_tests/__tests__/__snapshots__/exposed_path.test.mjs.md
  packages/api_tests/__tests__/__snapshots__/exposed_path.test.mjs.snap
  packages/option-t/src/ClassicOption/compat.ts
  packages/option-t/src/ClassicOption/index.ts
  packages/option-t/src/Option.ts
Labels: I-enhancement, A-API

#1584 Rename `isNotNullOrUndefined()` to `isNotNullAndUndefined()`
  packages/api_tests/__tests__/Maybe/expect.test.mjs
  packages/api_tests/__tests__/Maybe/type_guard.test.mjs
  packages/api_tests/__tests__/__snapshots__/exposed_path.test.mjs.md
  packages/api_tests/__tests__/__snapshots__/exposed_path.test.mjs.snap
  packages/option-t/src/ClassicOption/compat.ts
  packages/option-t/src/Maybe/Maybe.ts
  packages/option-t/src/Maybe/and.ts
  packages/option-t/src/Maybe/expect.ts
  packages/option-t/src/Maybe/index.ts
  packages/option-t/src/Maybe/inspect.ts
  packages/option-t/src/Maybe/map.ts
  packages/option-t/src/Maybe/mapAsync.ts
  packages/option-t/src/Maybe/mapOr.ts
  packages/option-t/src/Maybe/mapOrAsync.ts
  packages/option-t/src/Maybe/mapOrElse.ts
  packages/option-t/src/Maybe/mapOrElseAsync.ts
  packages/option-t/src/Maybe/orElseAsync.ts
  packages/option-t/src/Maybe/unwrapOr.ts
  packages/option-t/src/Maybe/unwrapOrElse.ts
  packages/option-t/src/Maybe/unwrapOrElseAsync.ts
  packages/option-t/src/Maybe/xor.ts
Labels: I-bug, A-API

#1585 Implement alternative that does not use `PlainOption` for `PlainResult/transpose`
  packages/api_tests/__tests__/PlainResult/transpose/to_nullable.test.mjs
  packages/api_tests/__tests__/PlainResult/transpose/to_plain_option.test.mjs
  packages/api_tests/__tests__/PlainResult/transpose/to_undefinable.test.mjs
  packages/api_tests/__tests__/__snapshots__/exposed_path.test.mjs.md
  packages/api_tests/__tests__/__snapshots__/exposed_path.test.mjs.snap
  packages/option-t/src/PlainResult/index.ts
  packages/option-t/src/PlainResult/transpose.ts
Labels: I-enhancement, A-API

#1591 Remove bors.toml
  bors.toml
Labels: I-cleanup, A-ops/repository

#1596 Add `make generate_import_path_list_md` to the root
  Makefile
Labels: I-enhancement, A-tools

#1598 Add legacy aliases to ClassiOption/ClassicResult
  packages/api_tests/__tests__/__snapshots__/exposed_path.test.mjs.md
  packages/api_tests/__tests__/__snapshots__/exposed_path.test.mjs.snap
  packages/option-t/src/ClassicOption/index.ts
  packages/option-t/src/ClassicResult/index.ts
  packages/option-t/src/Option.ts
  packages/option-t/src/Result.ts
Labels: I-enhancement, A-API

#1611 Add "Supported Environments" to README
  README.md
Labels: I-enhancement, A-documentation

#1599 Expose each of "core" operators directly
  packages/api_tests/__tests__/__snapshots__/exposed_path.test.mjs.md
  packages/api_tests/__tests__/__snapshots__/exposed_path.test.mjs.snap
  packages/option-t/src/Maybe/index.ts
  packages/option-t/src/Nullable/index.ts
  packages/option-t/src/PlainOption/index.ts
  packages/option-t/src/PlainResult/index.ts
  packages/option-t/src/Undefinable/index.ts
Labels: I-enhancement, A-API

#1615 Set `type=module` for all of package.json
  package.json
  packages/api_tests/package.json
Labels: I-enhancement, A-internal

#1616 Deprecated shortened exports
  packages/api_tests/__tests__/__snapshots__/exposed_path.test.mjs.md
  packages/api_tests/__tests__/__snapshots__/exposed_path.test.mjs.snap
  packages/api_tests/__tests__/exposed_path_table.mjs
  packages/option-t/package.json
  packages/option-t/src/Maybe/compat/index.ts
  packages/option-t/src/Maybe/index.ts
  packages/option-t/src/Nullable/compat/index.ts
  packages/option-t/src/Nullable/index.ts
  packages/option-t/src/PlainOption/compat/index.ts
  packages/option-t/src/PlainOption/index.ts
  packages/option-t/src/PlainResult/compat/index.ts
  packages/option-t/src/PlainResult/index.ts
  packages/option-t/src/Undefinable/compat/index.ts
  packages/option-t/src/Undefinable/index.ts
  packages/option-t/tools/pkg_files.json
  packages/option-t/tools/public_api/table.mjs
Labels: I-enhancement, A-API

#1617 Rename to <TypeName>/compat/v33
  packages/api_tests/__tests__/__snapshots__/exposed_path.test.mjs.md
  packages/api_tests/__tests__/__snapshots__/exposed_path.test.mjs.snap
  packages/api_tests/__tests__/exposed_path_table.mjs
  packages/option-t/package.json
  packages/option-t/src/Maybe/compat/v33.ts
  packages/option-t/src/Nullable/compat/v33.ts
  packages/option-t/src/PlainOption/compat/v33.ts
  packages/option-t/src/PlainResult/compat/v33.ts
  packages/option-t/src/Undefinable/compat/v33.ts
  packages/option-t/tools/pkg_files.json
  packages/option-t/tools/public_api/table.mjs
Labels: I-enhancement, A-API

#1618 Fix deprecation comments and alternative path
  packages/option-t/src/Maybe/compat/v33.ts
  packages/option-t/src/Nullable/compat/v33.ts
  packages/option-t/src/PlainOption/compat/v33.ts
  packages/option-t/src/PlainResult/compat/v33.ts
Labels: I-bug, A-documentation

#1626 Mark deprecated API which user should replace when they stop to use a compat path
  packages/option-t/src/Maybe/compat/v33.ts
  packages/option-t/src/Nullable/compat/v33.ts
  packages/option-t/src/PlainOption/compat/v33.ts
  packages/option-t/src/PlainResult/compat/v33.ts
  packages/option-t/src/Undefinable/compat/v33.ts
Labels: I-enhancement, A-documentation

#1627 Mark `and`/`equal`/`or` that are exported by `Plain{Option,Result}/index` deprecated
  packages/option-t/src/PlainOption/compat/v33.ts
  packages/option-t/src/PlainOption/index.ts
  packages/option-t/src/PlainResult/compat/v33.ts
  packages/option-t/src/PlainResult/index.ts
Labels: I-enhancement, A-API

#1631 Move to https://github.com/option-t/option-t
  CHANGELOG.md
  CHANGELOG_OLD.md
  README.md
  docs/wrapper_objects.md
  packages/option-t/package.json
  packages/option-t/src/ClassicOption/ClassicOption.d.ts
  packages/option-t/src/ClassicOption/ClassicOption.js
  packages/option-t/src/ClassicResult/ClassicResult.d.ts
  packages/option-t/src/ClassicResult/ClassicResult.js
  packages/option-t/src/Option.ts
  packages/option-t/src/PlainOption/Option.ts
  packages/option-t/src/PlainOption/index.ts
  packages/option-t/src/PlainResult/Result.ts
  packages/option-t/src/PlainResult/index.ts
  packages/option-t/src/Result.ts
Labels: I-cleanup, A-ops/repository

#1632 Enable `@typescript-eslint/no-import-type-side-effects` to prevent an accidental side-effect import
  packages/option-t/.eslintrc.cjs
  packages/option-t/src/PlainOption/okOr.ts
  packages/option-t/src/PlainOption/toNullable.ts
  packages/option-t/src/PlainOption/toUndefinable.ts
  packages/option-t/src/PlainResult/or.ts
  packages/option-t/src/PlainResult/orElse.ts
  packages/option-t/src/PlainResult/toOption.ts
Labels: I-cleanup, A-tools/lint

#1619 Do not emit `exports.__esModule` for commonjs
  packages/option-t/tools/babel/babelrc.cjs.mjs
Labels: I-breaking change, A-internal, I-cleanup

#1635 Remove compat `option-t/{cjs,esm,lib}/<TypeName>/index` path
  packages/api_tests/__tests__/__snapshots__/exposed_path.test.mjs.md
  packages/api_tests/__tests__/__snapshots__/exposed_path.test.mjs.snap
  packages/api_tests/__tests__/exposed_path_table.mjs
  packages/option-t/package.json
  packages/option-t/tools/public_api/table.mjs
Labels: A-API, I-breaking change, I-cleanup

#1597 Drop legacy `option-t/lib/{Option, Result}`
  docs/wrapper_objects.md
  packages/api_tests/__tests__/__snapshots__/exposed_path.test.mjs.md
  packages/api_tests/__tests__/__snapshots__/exposed_path.test.mjs.snap
  packages/api_tests/__tests__/exposed_path_table.mjs
  packages/option-t/package.json
  packages/option-t/src/Option.ts
  packages/option-t/src/Result.ts
  packages/option-t/tools/pkg_files.json
  packages/option-t/tools/public_api/table.mjs
Labels: A-API, I-breaking change

#1623 Remove deprecated APIs marked in v33.10.1
  docs/public_api_list.md
  packages/api_tests/__tests__/__snapshots__/exposed_path.test.mjs.md
  packages/api_tests/__tests__/__snapshots__/exposed_path.test.mjs.snap
  packages/option-t/src/Maybe/index.ts
  packages/option-t/src/Nullable/index.ts
  packages/option-t/src/PlainOption/index.ts
  packages/option-t/src/PlainResult/index.ts
  packages/option-t/src/Undefinable/index.ts
Labels: A-API, I-breaking change, I-cleanup

#1633 Add migration guide to v34
  docs/README.md
  docs/migration/v34.md
  packages/option-t/tools/pkg_files.json
Labels: I-enhancement, A-documentation

#1636 Deprecate the support for TypeScript's `--moduleResolution node`
  README.md
Labels: I-enhancement, A-documentation

#1638 Remove bors-ng specific branch config
  .github/workflows/ci_for_pr.yaml
Labels: I-cleanup, A-ops/repository

#1640 Set types field for "default" condition for each of dual exports
  packages/option-t/package.json
  packages/option-t/tools/package_json_rewriter/transformer/add_exports_field/ExportEntry.mjs
Labels: I-enhancement, A-internal

#1643 Fix typo in docs
  docs/operators_reverse_index.md
Labels: I-bug, A-documentation

#1656 Clean up the order of 'make clean'
  packages/option-t/Makefile
Labels: I-cleanup, A-tools/build

#1645 Allow `import * as TypeName from 'option-t/<TypeName>/namespace';`
  packages/api_tests/__tests__/__snapshots__/exposed_path.test.mjs.md
  packages/api_tests/__tests__/__snapshots__/exposed_path.test.mjs.snap
  packages/api_tests/__tests__/exposed_path_table.mjs
  packages/option-t/package.json
  packages/option-t/src/Maybe/namespace.ts
  packages/option-t/src/Nullable/namespace.ts
  packages/option-t/src/PlainOption/namespace.ts
  packages/option-t/src/PlainResult/namespace.ts
  packages/option-t/src/Undefinable/namespace.ts
  packages/option-t/tools/pkg_files.json
  packages/option-t/tools/public_api/table.mjs
Labels: I-enhancement, A-API

#1657 Add `okrOr` and `okOrElse` to `<TypeName>/namespace`
  packages/api_tests/__tests__/__snapshots__/exposed_path.test.mjs.md
  packages/api_tests/__tests__/__snapshots__/exposed_path.test.mjs.snap
  packages/option-t/src/Maybe/namespace.ts
  packages/option-t/src/Nullable/namespace.ts
  packages/option-t/src/PlainOption/namespace.ts
  packages/option-t/src/Undefinable/namespace.ts
Labels: I-enhancement, A-API

#1658 Update docs/public_api_list.md
  docs/public_api_list.md
Labels: I-enhancement, A-documentation

#1649 Remove unnecessary index export
  packages/api_tests/__tests__/__snapshots__/exposed_path.test.mjs.md
  packages/api_tests/__tests__/__snapshots__/exposed_path.test.mjs.snap
  packages/api_tests/__tests__/exposed_path_table.mjs
  packages/option-t/package.json
  packages/option-t/tools/public_api/table.mjs
Labels: A-API, I-breaking change, I-cleanup

#1660 Simplify the order of type parameters
  packages/option-t/src/PlainResult/orElse.ts
  packages/option-t/src/PlainResult/orElseAsync.ts
Labels: A-API, I-breaking change, I-cleanup
