Repository option-t/option-t, pull requests merged in 2024-10, with the labels that each got.

#2364 Do not touch object properties directly for plain result
  packages/option-t/src/plain_option/from_result.ts
  packages/option-t/src/plain_option/transpose.ts
  packages/option-t/src/plain_result/and.ts
  packages/option-t/src/plain_result/and_then.ts
  packages/option-t/src/plain_result/and_then_async.ts
  packages/option-t/src/plain_result/as_mut.ts
  packages/option-t/src/plain_result/deprecated/unwrap_or_throw_error.ts
  packages/option-t/src/plain_result/deprecated/unwrap_or_throw_unknown.ts
  packages/option-t/src/plain_result/drop.ts
  packages/option-t/src/plain_result/equal.ts
  packages/option-t/src/plain_result/inspect.ts
  packages/option-t/src/plain_result/internal/intrinsics_compare.ts
  packages/option-t/src/plain_result/internal/intrinsics_unsafe.ts
  packages/option-t/src/plain_result/internal/mutable.ts
  packages/option-t/src/plain_result/internal/unwrap_err_or.ts
  packages/option-t/src/plain_result/is_err_and.ts
  packages/option-t/src/plain_result/is_ok_and.ts
  packages/option-t/src/plain_result/map.ts
  packages/option-t/src/plain_result/map_async.ts
  packages/option-t/src/plain_result/map_err.ts
  packages/option-t/src/plain_result/map_err_async.ts
  packages/option-t/src/plain_result/map_or.ts
  packages/option-t/src/plain_result/map_or_async.ts
  packages/option-t/src/plain_result/map_or_else.ts
  packages/option-t/src/plain_result/map_or_else_async.ts
  packages/option-t/src/plain_result/or.ts
  packages/option-t/src/plain_result/or_else.ts
  packages/option-t/src/plain_result/or_else_async.ts
  packages/option-t/src/plain_result/result.ts
  packages/option-t/src/plain_result/transpose.ts
  packages/option-t/src/plain_result/try_catch.ts
  packages/option-t/src/plain_result/try_catch_async.ts
  packages/option-t/src/plain_result/unwrap_or.ts
  packages/option-t/src/plain_result/unwrap_or_else.ts
  packages/option-t/src/plain_result/unwrap_or_else_async.ts
  packages/option-t/src/plain_result/unwrap_or_throw.ts
  packages/option-t/tools/__tests__/__snapshots__/distribution_contain_all.test.mjs.md
  packages/option-t/tools/__tests__/__snapshots__/distribution_contain_all.test.mjs.snap
Labels: I-refactor, A-internal

#2365 Use public API as possible for testing for plain result
  packages/api_tests/__tests__/plain_option/transpose/to_plain_option.test.mjs
  packages/api_tests/__tests__/plain_option/transpose/to_result.test.mjs
  packages/api_tests/__tests__/plain_result/and.test.mjs
  packages/api_tests/__tests__/plain_result/and_then.test.mjs
  packages/api_tests/__tests__/plain_result/and_then_async.test.mjs
  packages/api_tests/__tests__/plain_result/create.test.mjs
  packages/api_tests/__tests__/plain_result/drop/test_drop_both.test.mjs
  packages/api_tests/__tests__/plain_result/drop/test_drop_err.test.mjs
  packages/api_tests/__tests__/plain_result/drop/test_drop_ok.test.mjs
  packages/api_tests/__tests__/plain_result/flatten.test.mjs
  packages/api_tests/__tests__/plain_result/map.test.mjs
  packages/api_tests/__tests__/plain_result/map_async.test.mjs
  packages/api_tests/__tests__/plain_result/map_err.test.mjs
  packages/api_tests/__tests__/plain_result/map_err_async.test.mjs
  packages/api_tests/__tests__/plain_result/or.test.mjs
  packages/api_tests/__tests__/plain_result/transpose/to_nullable.test.mjs
  packages/api_tests/__tests__/plain_result/transpose/to_undefinable.test.mjs
Labels: I-cleanup, A-tools/testing

#2363 docs: add idiom of infer utility types
  docs/idiom/README.md
  docs/idiom/infer.md
Labels: I-enhancement, A-documentation

#2366 v49.2.1
  packages/api_tests/package.json
  packages/option-t/package.json
  packages/test_module_resolution_bundler/package.json
  packages/test_module_resolution_node16/package.json
Labels: I-enhancement, A-ops/release-engineering

#2373 Fix ESLint warnings about `import/order`
  packages/api_tests/__tests__/plain_result/drop/test_drop_ok.test.mjs
  packages/option-t/src/plain_result/drop.ts
  packages/option-t/src/plain_result/try_catch.ts
  packages/option-t/src/plain_result/try_catch_async.ts
Labels: A-internal, I-cleanup

#2381 Add tests that checks loads actual same module via `import()` and `require()`
  packages/api_tests/__tests__/exposed_path/helper.mjs
Labels: I-enhancement, A-internal

#2382 add support for module-sync
  packages/option-t/package.json
  packages/option-t/tools/package_json_rewriter/transformer/add_exports_field/export_entry.mjs
  packages/option-t/tools/test_package_json_exports_field_format.mjs
Labels: I-enhancement, A-internal

#2379 ci: Add Node v23 for unint test job
  .github/workflows/_ci.yaml
Labels: I-enhancement, A-ops/CI

#2383 v49.3.0
  packages/api_tests/package.json
  packages/option-t/package.json
  packages/test_module_resolution_bundler/package.json
  packages/test_module_resolution_node16/package.json
Labels: I-enhancement, A-ops/release-engineering

#2378 Move public APIs that do unsafe operations into `unsafe/` subdirs
  docs/public_api_list.md
  packages/api_tests/__tests__/exposed_path/__snapshots__/plain_option.test.mjs.md
  packages/api_tests/__tests__/exposed_path/__snapshots__/plain_option.test.mjs.snap
  packages/api_tests/__tests__/exposed_path/__snapshots__/plain_result.test.mjs.md
  packages/api_tests/__tests__/exposed_path/__snapshots__/plain_result.test.mjs.snap
  packages/api_tests/__tests__/exposed_path/plain_option.test.mjs
  packages/api_tests/__tests__/exposed_path/plain_result.test.mjs
  packages/api_tests/__tests__/plain_option/as_mut.test.mjs
  packages/api_tests/__tests__/plain_option/drop.test.mjs
  packages/api_tests/__tests__/plain_result/as_mut.test.mjs
  packages/api_tests/__tests__/plain_result/drop/test_drop_both.test.mjs
  packages/api_tests/__tests__/plain_result/drop/test_drop_err.test.mjs
  packages/api_tests/__tests__/plain_result/drop/test_drop_ok.test.mjs
  packages/option-t/package.json
  packages/option-t/src/internal/assert.ts
  packages/option-t/src/plain_option/index.ts
  packages/option-t/src/plain_option/unsafe/as_mut.ts
  packages/option-t/src/plain_option/unsafe/drop.ts
  packages/option-t/src/plain_result/internal/intermediate_namespace.ts
  packages/option-t/src/plain_result/unsafe/as_mut.ts
  packages/option-t/src/plain_result/unsafe/drop.ts
  packages/option-t/tools/__tests__/__snapshots__/distribution_contain_all.test.mjs.md
  packages/option-t/tools/__tests__/__snapshots__/distribution_contain_all.test.mjs.snap
  packages/option-t/tools/public_api/table.mjs
  packages/test_module_resolution_bundler/src/plain_option.cts
  packages/test_module_resolution_bundler/src/plain_option.mts
  packages/test_module_resolution_bundler/src/plain_result.cts
  packages/test_module_resolution_bundler/src/plain_result.mts
  packages/test_module_resolution_node16/src/plain_option.cts
  packages/test_module_resolution_node16/src/plain_option.mts
  packages/test_module_resolution_node16/src/plain_result.cts
  packages/test_module_resolution_node16/src/plain_result.mts
Labels: A-API, B-breaking change, I-cleanup, S-needs-rebase

#2391 v50.0.0
  packages/api_tests/package.json
  packages/option-t/package.json
  packages/test_module_resolution_bundler/package.json
  packages/test_module_resolution_node16/package.json
Labels: I-enhancement, A-ops/release-engineering

#2393 Update pnpm to v9.12.2 by `corepack up`
  package.json
Labels: I-enhancement, A-tools

#2394 Add the link for v50 release note to docs/migration/README.md
  docs/migration/README.md
Labels: I-enhancement, A-documentation

#2395 Implement `is_some_and()` operator for `Nullable`
  docs/public_api_list.md
  packages/api_tests/__tests__/exposed_path/__snapshots__/nullable.test.mjs.md
  packages/api_tests/__tests__/exposed_path/__snapshots__/nullable.test.mjs.snap
  packages/api_tests/__tests__/exposed_path/nullable.test.mjs
  packages/api_tests/__tests__/nullable/is_some_and/is_some_and.null.test.mjs
  packages/api_tests/__tests__/nullable/is_some_and/is_some_and.some.test.mjs
  packages/api_tests/__tests__/nullable/is_some_and/is_some_and.undefined.test.mjs
  packages/api_tests/__tests__/nullable/is_some_and/is_some_and_with_ensure_type.null.test.mjs
  packages/api_tests/__tests__/nullable/is_some_and/is_some_and_with_ensure_type.some.test.mjs
  packages/api_tests/__tests__/nullable/is_some_and/is_some_and_with_ensure_type.undefined.test.mjs
  packages/option-t/package.json
  packages/option-t/src/nullable/index.ts
  packages/option-t/src/nullable/internal/intermediate_namespace.ts
  packages/option-t/src/nullable/is_some_and.ts
  packages/option-t/tools/__tests__/__snapshots__/distribution_contain_all.test.mjs.md
  packages/option-t/tools/__tests__/__snapshots__/distribution_contain_all.test.mjs.snap
  packages/option-t/tools/public_api/table.mjs
  packages/test_module_resolution_bundler/src/nullable.cts
  packages/test_module_resolution_bundler/src/nullable.mts
  packages/test_module_resolution_node16/src/nullable.cts
  packages/test_module_resolution_node16/src/nullable.mts
Labels: I-enhancement, A-API

#2396 Implement `is_some_and()` operator for `Maybe`
  docs/public_api_list.md
  packages/api_tests/__tests__/exposed_path/__snapshots__/maybe.test.mjs.md
  packages/api_tests/__tests__/exposed_path/__snapshots__/maybe.test.mjs.snap
  packages/api_tests/__tests__/exposed_path/maybe.test.mjs
  packages/api_tests/__tests__/maybe/is_some_and/is_some_and.null.test.mjs
  packages/api_tests/__tests__/maybe/is_some_and/is_some_and.some.test.mjs
  packages/api_tests/__tests__/maybe/is_some_and/is_some_and.undefined.test.mjs
  packages/api_tests/__tests__/maybe/is_some_and/is_some_and_with_ensure_type.null.test.mjs
  packages/api_tests/__tests__/maybe/is_some_and/is_some_and_with_ensure_type.some.test.mjs
  packages/api_tests/__tests__/maybe/is_some_and/is_some_and_with_ensure_type.undefined.test.mjs
  packages/option-t/package.json
  packages/option-t/src/maybe/index.ts
  packages/option-t/src/maybe/internal/intermediate_namespace.ts
  packages/option-t/src/maybe/is_some_and.ts
  packages/option-t/tools/__tests__/__snapshots__/distribution_contain_all.test.mjs.md
  packages/option-t/tools/__tests__/__snapshots__/distribution_contain_all.test.mjs.snap
  packages/option-t/tools/public_api/table.mjs
  packages/test_module_resolution_bundler/src/maybe.cts
  packages/test_module_resolution_bundler/src/maybe.mts
  packages/test_module_resolution_node16/src/maybe.cts
  packages/test_module_resolution_node16/src/maybe.mts
Labels: I-enhancement, A-API

#2397 Implement `is_some_and()` operator for `Undefinable`
  docs/public_api_list.md
  packages/api_tests/__tests__/exposed_path/__snapshots__/undefinable.test.mjs.md
  packages/api_tests/__tests__/exposed_path/__snapshots__/undefinable.test.mjs.snap
  packages/api_tests/__tests__/exposed_path/undefinable.test.mjs
  packages/api_tests/__tests__/undefinable/is_some_and/is_some_and.null.test.mjs
  packages/api_tests/__tests__/undefinable/is_some_and/is_some_and.some.test.mjs
  packages/api_tests/__tests__/undefinable/is_some_and/is_some_and.undefined.test.mjs
  packages/api_tests/__tests__/undefinable/is_some_and/is_some_and_with_ensure_type.null.test.mjs
  packages/api_tests/__tests__/undefinable/is_some_and/is_some_and_with_ensure_type.some.test.mjs
  packages/api_tests/__tests__/undefinable/is_some_and/is_some_and_with_ensure_type.undefined.test.mjs
  packages/option-t/package.json
  packages/option-t/src/undefinable/index.ts
  packages/option-t/src/undefinable/internal/intermediate_namespace.ts
  packages/option-t/src/undefinable/is_some_and.ts
  packages/option-t/tools/__tests__/__snapshots__/distribution_contain_all.test.mjs.md
  packages/option-t/tools/__tests__/__snapshots__/distribution_contain_all.test.mjs.snap
  packages/option-t/tools/public_api/table.mjs
  packages/test_module_resolution_bundler/src/undefinable.cts
  packages/test_module_resolution_bundler/src/undefinable.mts
  packages/test_module_resolution_node16/src/undefinable.cts
  packages/test_module_resolution_node16/src/undefinable.mts
Labels: I-enhancement, A-API

#2398 Revert `is_some_and` for Nullable, Maybe, and Undefinable.
  docs/public_api_list.md
  packages/api_tests/__tests__/exposed_path/__snapshots__/maybe.test.mjs.md
  packages/api_tests/__tests__/exposed_path/__snapshots__/maybe.test.mjs.snap
  packages/api_tests/__tests__/exposed_path/__snapshots__/nullable.test.mjs.md
  packages/api_tests/__tests__/exposed_path/__snapshots__/nullable.test.mjs.snap
  packages/api_tests/__tests__/exposed_path/__snapshots__/undefinable.test.mjs.md
  packages/api_tests/__tests__/exposed_path/__snapshots__/undefinable.test.mjs.snap
  packages/api_tests/__tests__/exposed_path/maybe.test.mjs
  packages/api_tests/__tests__/exposed_path/nullable.test.mjs
  packages/api_tests/__tests__/exposed_path/undefinable.test.mjs
  packages/api_tests/__tests__/maybe/is_some_and/is_some_and.null.test.mjs
  packages/api_tests/__tests__/maybe/is_some_and/is_some_and.some.test.mjs
  packages/api_tests/__tests__/maybe/is_some_and/is_some_and.undefined.test.mjs
  packages/api_tests/__tests__/maybe/is_some_and/is_some_and_with_ensure_type.null.test.mjs
  packages/api_tests/__tests__/maybe/is_some_and/is_some_and_with_ensure_type.some.test.mjs
  packages/api_tests/__tests__/maybe/is_some_and/is_some_and_with_ensure_type.undefined.test.mjs
  packages/api_tests/__tests__/nullable/is_some_and/is_some_and.null.test.mjs
  packages/api_tests/__tests__/nullable/is_some_and/is_some_and.some.test.mjs
  packages/api_tests/__tests__/nullable/is_some_and/is_some_and.undefined.test.mjs
  packages/api_tests/__tests__/nullable/is_some_and/is_some_and_with_ensure_type.null.test.mjs
  packages/api_tests/__tests__/nullable/is_some_and/is_some_and_with_ensure_type.some.test.mjs
  packages/api_tests/__tests__/nullable/is_some_and/is_some_and_with_ensure_type.undefined.test.mjs
  packages/api_tests/__tests__/undefinable/is_some_and/is_some_and.null.test.mjs
  packages/api_tests/__tests__/undefinable/is_some_and/is_some_and.some.test.mjs
  packages/api_tests/__tests__/undefinable/is_some_and/is_some_and.undefined.test.mjs
  packages/api_tests/__tests__/undefinable/is_some_and/is_some_and_with_ensure_type.null.test.mjs
  packages/api_tests/__tests__/undefinable/is_some_and/is_some_and_with_ensure_type.some.test.mjs
  packages/api_tests/__tests__/undefinable/is_some_and/is_some_and_with_ensure_type.undefined.test.mjs
  packages/option-t/package.json
  packages/option-t/src/maybe/index.ts
  packages/option-t/src/maybe/internal/intermediate_namespace.ts
  packages/option-t/src/maybe/is_some_and.ts
  packages/option-t/src/nullable/index.ts
  packages/option-t/src/nullable/internal/intermediate_namespace.ts
  packages/option-t/src/nullable/is_some_and.ts
  packages/option-t/src/undefinable/index.ts
  packages/option-t/src/undefinable/internal/intermediate_namespace.ts
  packages/option-t/src/undefinable/is_some_and.ts
  packages/option-t/tools/__tests__/__snapshots__/distribution_contain_all.test.mjs.md
  packages/option-t/tools/__tests__/__snapshots__/distribution_contain_all.test.mjs.snap
  packages/option-t/tools/public_api/table.mjs
  packages/test_module_resolution_bundler/src/maybe.cts
  packages/test_module_resolution_bundler/src/maybe.mts
  packages/test_module_resolution_bundler/src/nullable.cts
  packages/test_module_resolution_bundler/src/nullable.mts
  packages/test_module_resolution_bundler/src/undefinable.cts
  packages/test_module_resolution_bundler/src/undefinable.mts
  packages/test_module_resolution_node16/src/maybe.cts
  packages/test_module_resolution_node16/src/maybe.mts
  packages/test_module_resolution_node16/src/nullable.cts
  packages/test_module_resolution_node16/src/nullable.mts
  packages/test_module_resolution_node16/src/undefinable.cts
  packages/test_module_resolution_node16/src/undefinable.mts
Labels: I-enhancement, A-API
